export const planDescription = [
  {
    id: 'A12B34CD',
    title: '미국 LA 여행 계획',
    location: 'United States, Los Angeles, CA',
    date: '2023 9. 24 - 10. 4',
    isRecord: true,
    isDraft: false,
    detailDescription: [
      {
        day: 1,
        country: '일본',
        location: '1 Chome Dotonbori, Chuo Ward, Osaka, 542-0071 도쿄',
        description:
          '안녕하세요! 일본을 누비며 맛있는 여행을 즐겨보았어요. 오사카의 타코야끼, 도쿄의 초밥, 교토의 유자라멘과 함께한 식도락 여행은 정말 특별했습니다. 현지 음식과 문화의 매력을 느끼며 여행의 색다른 맛을 만끽할 수 있었어요....',
      },
      {
        day: 2,
        country: '일본',
        location: '1 Chome Dotonbori, Chuo Ward, Osaka, 542-0071 도쿄',
        description: '',
      },
    ],
  },
  {
    id: 'E56F78GH',
    title: '태국 일주일 여행 계획2',
    location: 'Thailand, Bangkok',
    date: '2022 6. 12 - 6. 20',
    isRecord: false,
    isDraft: false,
  },
  {
    id: 'I90J12KL',
    title: '미국 LA 여행 계획3',
    location: 'United States, Los Angeles, CA ',
    date: '2023 9. 24 - 10. 4',
    isRecord: false,
    isDraft: false,
  },
  {
    id: 'M34N56OP',
    title: '미국 LA 여행 계획4',
    location: 'United States, Los Angeles, CA ',
    date: '2023 9. 24 - 10. 4',
    isRecord: false,
    isDraft: false,
  },
  {
    id: 'Q78R90ST',
    title: '미국 여행 작성중',
    location: 'United States, Los Angeles, CA ',
    date: '2023 9. 24 - 10. 4',
    isRecord: false,
    isDraft: true,
  },
  {
    id: 'U12V34WX',
    title: '태국 여행 쓰는중',
    location: 'United States, Los Angeles, CA ',
    date: '2023 9. 24 - 10. 4',
    isRecord: false,
    isDraft: true,
  },
];
